name: CI/CD Pipeline with OWASP ZAP

on:
  workflow_dispatch

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Docker network
        run: docker network create taller-network

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Paso 3: Construir la imagen Docker de la aplicación
      - name: Build Docker image
        run: docker build -t backend:latest .

      # Paso 4: Iniciar el contenedor Docker en segundo plano
      - name: Run Docker container
        run: docker run -d -p 3100:3100 --network taller-network --name backend_container backend:latest

      # Esperar unos segundos para asegurarse de que la aplicación esté en ejecución
      - name: Wait for app to start
        run: sleep 15

      # Paso 5: Realizar pruebas con OWASP ZAP
      - name: ZAP Scan
        uses: zaproxy/action-baseline@41aee98ebc7cf2802c3beae4e7d4336413a21e43 # v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://backend_container:3100'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'

      # Paso 6: Subir el reporte de OWASP ZAP como un artefacto
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP Report
          path: zap-report.htm