name: CI/CD Pipeline with OWASP ZAP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '35 9 * * 5'

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Paso 3: Construir la imagen Docker de la aplicación
      - name: Build Docker image
        run: docker build -t backend:latest .

      # Paso 4: Iniciar el contenedor Docker en segundo plano
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name backend_container myapp:latest

      # Esperar unos segundos para asegurarse de que la aplicación esté en ejecución
      - name: Wait for app to start
        run: sleep 15

      # Paso 5: Realizar pruebas con OWASP ZAP
      - name: OWASP ZAP full scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: 'http://localhost:3100'
          rules_file_name: '.zap/rules.tsv'
          docker_name: 'zap'
          generate_report: true
          report_html: 'zap-report.html'

      # Paso 6: Subir el reporte de OWASP ZAP como un artefacto
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ZAP Report
          path: zap-report.htm